using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using MvvmCross.Droid.Views;
using MvvmCross.Droid.Support.V7.AppCompat;
using BCC.Core.ViewModels;
using MvvmCross.Plugins.Messenger;
using MvvmCross.Platform;

namespace BCC.Droid.Views
{
    [Activity(Label = "Add Vehicle Profiles", NoHistory = true)]
    public class AddVehicleView : MvxAppCompatActivity<AddVehiclesViewModel>
    {
        /// <summary>
        /// Use OnViewModelSet to inflate the view's ContentView from AXML.
        /// </summary>
        protected override void OnViewModelSet()
        {
            // This uses a resource identifier generated by Android to identify the view.
            SetContentView(Resource.Layout.AddVehicle);

            //Setting up the layout for the toolbar 
            var toolbar = FindViewById<Android.Support.V7.Widget.Toolbar>(Resource.Id.toolbar);
            SetSupportActionBar(toolbar);
            SupportActionBar.Title = "Add Profile";//all you really need to change is this
            SupportActionBar.SetDisplayHomeAsUpEnabled(true);
            SupportActionBar.SetHomeButtonEnabled(true);
            SupportActionBar.SetDisplayShowHomeEnabled(true);
            SupportActionBar.SetHomeAsUpIndicator(Resource.Drawable.back);
        }
        /// <summary>
        /// This detects if any of the buttons in the toolbar have been pressed
        /// </summary>
        /// <param name="item">the item that was pressed</param>
        /// <returns></returns>
        public override bool OnOptionsItemSelected(IMenuItem item)
        {
            switch (item.ItemId)//this is the case for the home button (the only button that can be left of the text in the header)
            {
                case Android.Resource.Id.Home:
                    IMvxMessenger messenger = Mvx.Resolve<IMvxMessenger>();
                    var message = new ViewModelCommunication(this, "reload");
                    messenger.Publish(message);
                    Finish();//go back
                    return true;

                default:
                    return base.OnOptionsItemSelected(item);
            }

        }
    }
}
